### ISSUE TITLE
Mac Error 

### ISSUE THREAD

**Issue by BoogiemanMedia** [rupeshs/diffusionmagic#11]
Hi I tried installing and it gives an error with micromamba command. Thanks!

Last login: Thu Oct  5 09:27:51 on console

The default interactive shell is now zsh.
FerMacBookPro3:~ fernandorajlevsky$ chmod +x /Users/fernandorajlevsky/Downloads/diffusionmagic-main/install-mac.sh 
FerMacBookPro3:~ fernandorajlevsky$ /Users/fernandorajlevsky/Downloads/diffusionmagic-main/install-mac.sh 
chmod: /Users/fernandorajlevsky/tools/mac/micromamba: No such file or directory
chmod: start.sh: No such file or directory
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/install-mac.sh: line 6: /Users/fernandorajlevsky/tools/mac/micromamba: No such file or directory
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/install-mac.sh: line 7: /Users/fernandorajlevsky/tools/mac/micromamba: No such file or directory
Diffusion magic installation completed,press any key to continue... FerMacBookPrmagic-main/start.sh ky$ /Users/fernandorajlevsky/Downloads/diffusion 
-bash: /Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh: Permission denied
FerMacBookPro3:~ fernandorajlevsky$ /Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh 
-bash: /Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh: Permission denied
FerMacBookPro3:~ fernandorajlevsky$ chmod +x /Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh 
FerMacBookPro3:~ fernandorajlevsky$ /Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh 
Starting DiffusionMagic please wait...
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh: line 5: micromamba: command not found
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh: line 6: micromamba: command not found

**Comment by rupeshs** [comment]
@BoogiemanMedia  Please enter into DiffusionMagic extracted directory and run all instructions

**Comment by BoogiemanMedia** [comment]
Thank you @rupeshs! 
I looked at it again and found out a lot of things I was not doing. Managed to install mamba but there seems to be something with the video card, asking for Cuda drivers maybe? I am in an M1 Max. Any ideas? Thanks!

FerMacBookPro3:~ fernandorajlevsky$ /Users/fernandorajlevsky/Downloads/diffusionmagic-main/install-mac.sh 

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pytorch/osx-arm64                                           Using cache
pytorch/noarch                                              Using cache
nvidia/osx-arm64                                            Using cache
nvidia/noarch                                               Using cache
pkgs/r/osx-arm64                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/main/osx-arm64                                           No change
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - nothing provides cuda 11.7.* needed by pytorch-cuda-11.7-h67b0de4_0
    
    The environment can't be solved, aborting the operation
    
critical libmamba Could not solve for environment specs
Modifying RC file "/Users/fernandorajlevsky/.bash_profile"
Generating config for root prefix "/Users/fernandorajlevsky/umamba"
Setting mamba executable to: "/Users/fernandorajlevsky/tools/mac/micromamba"Adding (or replacing) the following in your "/Users/fernandorajlevsky/.bash_profile" file

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/Users/fernandorajlevsky/tools/mac/micromamba";
export MAMBA_ROOT_PREFIX="/Users/fernandorajlevsky/umamba";
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    if [ -f "/Users/fernandorajlevsky/umamba/etc/profile.d/micromamba.sh" ]; then
        . "/Users/fernandorajlevsky/umamba/etc/profile.d/micromamba.sh"
    else
        export  PATH="/Users/fernandorajlevsky/umamba/bin:$PATH"  # extra space after export prevents interference from conda init
    fi
fi
unset __mamba_setup
# <<< mamba initialize <<<

Diffusion magic installation completed,press any key to continue...
FerMacBookPro3:~ fernandorajlevsky$ /Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh 
Starting DiffusionMagic please wait...
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh: line 5: micromamba: command not found
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/start.sh: line 6: micromamba: command not found
FerMacBookPro3:~ fernandorajlevsky$

**Comment by rupeshs** [comment]
@BoogiemanMedia  I don't have a Mac machine, I have tested this on Windows and Linux.
https://github.com/rupeshs/diffusionmagic#how-to-install-and-run-on-mac-not-tested
Feel free to create PRs

**Comment by vicento** [comment]
On M1 Max MacOS 14.1 i have the same error at installation :


```
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - nothing provides cuda 11.7.* needed by pytorch-cuda-11.7-h67b0de4_0
    
    The environment can't be solved, aborting the operation
    
critical libmamba Could not solve for environment specs
Modifying RC file "/Users/stephane/.bash_profile"
Generating config for root prefix "/Users/stephane/diffusionmagic/umamba"
Setting mamba executable to: "/Users/stephane/diffusionmagic/tools/mac/micromamba"Adding (or replacing) the following in your "/Users/stephane/.bash_profile" file

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/Users/stephane/diffusionmagic/tools/mac/micromamba";
export MAMBA_ROOT_PREFIX="/Users/stephane/diffusionmagic/umamba";
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    if [ -f "/Users/stephane/diffusionmagic/umamba/etc/profile.d/micromamba.sh" ]; then
        . "/Users/stephane/diffusionmagic/umamba/etc/profile.d/micromamba.sh"
    else
        export  PATH="/Users/stephane/diffusionmagic/umamba/bin:$PATH"  # extra space after export prevents interference from conda init
    fi
fi
unset __mamba_setup
# <<< mamba initialize <<<

Diffusion magic installation completed,press any key to continue...
```

**Comment by vicento** [comment]
the "same issue" is discussed here : https://github.com/conda-forge/miniforge/issues/255

**Comment by vicento** [comment]
have tried to instal micro mamba with homebrew : 
`brew install micromamba`
but without success and have this error now :
```
Starting DiffusionMagic please wait...
Traceback (most recent call last):
  File "/Users/stephane/diffusionmagic/src/app.py", line 3, in <module>
    from backend.computing import Computing
  File "/Users/stephane/diffusionmagic/src/backend/computing.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by BoogiemanMedia** [comment]
Hi! thank you for your message. I managed to install micromamba and bypass the CUDA error and I got to the app running until I get the local link working (Running on local URL:  http://127.0.0.1:7860). All good there. But when trying to execute app.py I get an error of incompatibility I couldn't solve.

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing stable diffusion xl pipeline
StableDiffusion - mps,torch.float16
using model stabilityai/stable-diffusion-xl-base-1.0
Fetching 18 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 26.56it/s]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.84s/it]
Model loaded in 14.56s 
loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): **error: input types 'tensor<1x77x1xf16>' and 'tensor<1xf32>' are not broadcast compatible**
LLVM ERROR: Failed to infer result type(s).
/Users/fernandorajlevsky/Downloads/diffusionmagic-main/start_fixed.sh: line 13: 20067 Abort trap: 6           python $APP_PATH
FerMacBookPro3:~ fernandorajlevsky$ /Users/fernandorajlevsky/Downloads/diffusionmagic-main/env/envs/diffusionmagic-env/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by rupeshs** [comment]
@BoogiemanMedia @vicento 
I have removed micromamba. Can you try this
`git clone https://github.com/rupeshs/diffusionmagic/`
`cd diffusionmagic`
`chmod +x install-mac.sh`
`./install.sh`
start using `start.sh`

**Comment by vicento** [comment]
Hi Rupeshs, thanks for your reply.
change 
`./install.sh`
 to ->
`./install-mac.sh`

**_i get an error :_** 
Starting DiffusionMagic env installation...
Found python command
Python version : 3.11.6
ERROR: Invalid requirement: 'torchvision=0.15.2'
Hint: = is not a valid operator. Did you mean == ?

**Comment by rupeshs** [comment]
@vicento Fixed it, can you do `git pull` and run again

**Comment by vicento** [comment]
ok, got an error : 
➜  diffusionmagic git:(main) ✗ ./install-mac.sh                           
Starting DiffusionMagic env installation...
Found python command
Python version : 3.11.6
Requirement already satisfied: torch==2.0.1 in ./env/lib/python3.11/site-packages (2.0.1)
Requirement already satisfied: torchvision==0.15.2 in ./env/lib/python3.11/site-packages (0.15.2)
Requirement already satisfied: filelock in ./env/lib/python3.11/site-packages (from torch==2.0.1) (3.13.1)
Requirement already satisfied: typing-extensions in ./env/lib/python3.11/site-packages (from torch==2.0.1) (4.8.0)
Requirement already satisfied: sympy in ./env/lib/python3.11/site-packages (from torch==2.0.1) (1.12)
Requirement already satisfied: networkx in ./env/lib/python3.11/site-packages (from torch==2.0.1) (3.2.1)
Requirement already satisfied: jinja2 in ./env/lib/python3.11/site-packages (from torch==2.0.1) (3.1.2)
Requirement already satisfied: numpy in ./env/lib/python3.11/site-packages (from torchvision==0.15.2) (1.26.1)
Requirement already satisfied: requests in ./env/lib/python3.11/site-packages (from torchvision==0.15.2) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./env/lib/python3.11/site-packages (from torchvision==0.15.2) (10.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib/python3.11/site-packages (from jinja2->torch==2.0.1) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./env/lib/python3.11/site-packages (from requests->torchvision==0.15.2) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.11/site-packages (from requests->torchvision==0.15.2) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./env/lib/python3.11/site-packages (from requests->torchvision==0.15.2) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.11/site-packages (from requests->torchvision==0.15.2) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in ./env/lib/python3.11/site-packages (from sympy->torch==2.0.1) (1.3.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Collecting accelerate==0.23.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 1))
  Obtaining dependency information for accelerate==0.23.0 from https://files.pythonhosted.org/packages/d9/92/2d3aecf9f4a192968035880be3e2fc8b48d541c7128f7c936f430d6f96da/accelerate-0.23.0-py3-none-any.whl.metadata
  Using cached accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)
Collecting diffusers==0.21.1 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 2))
  Using cached diffusers-0.21.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gradio==3.39.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 3))
  Obtaining dependency information for gradio==3.39.0 from https://files.pythonhosted.org/packages/82/5f/c815ae438b63ca8b7418acf470369493bac5aa267192702c8601ca67966b/gradio-3.39.0-py3-none-any.whl.metadata
  Using cached gradio-3.39.0-py3-none-any.whl.metadata (17 kB)
Collecting safetensors==0.3.1 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 4))
  Using cached safetensors-0.3.1-cp311-cp311-macosx_12_0_arm64.whl (401 kB)
Collecting scipy==1.10.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 5))
  Using cached scipy-1.10.0-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Collecting transformers==4.33.2 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 6))
  Obtaining dependency information for transformers==4.33.2 from https://files.pythonhosted.org/packages/1a/06/3817f9bb923437ead9a794f0ac0d03b8b5e0478ab112db4c413dd37c09da/transformers-4.33.2-py3-none-any.whl.metadata
  Using cached transformers-4.33.2-py3-none-any.whl.metadata (119 kB)
Collecting pydantic==1.10.4 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 7))
  Using cached pydantic-1.10.4-cp311-cp311-macosx_11_0_arm64.whl (2.5 MB)
Collecting mypy==1.0.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 8))
  Using cached mypy-1.0.0-cp311-cp311-macosx_11_0_arm64.whl (10.3 MB)
Collecting black==23.1.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 9))
  Using cached black-23.1.0-cp311-cp311-macosx_10_16_universal2.whl (2.6 MB)
Collecting flake8==6.0.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 10))
  Using cached flake8-6.0.0-py2.py3-none-any.whl (57 kB)
Requirement already satisfied: markupsafe==2.1.3 in ./env/lib/python3.11/site-packages (from -r /Users/stephane/diffusionmagic/requirements.txt (line 11)) (2.1.3)
Collecting opencv-contrib-python==4.7.0.72 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 12))
  Using cached opencv_contrib_python-4.7.0.72-cp37-abi3-macosx_11_0_arm64.whl (41.0 MB)
Collecting controlnet-aux==0.0.1 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 13))
  Using cached controlnet_aux-0.0.1-py3-none-any.whl (26 kB)
Collecting invisible-watermark==0.2.0 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 14))
  Obtaining dependency information for invisible-watermark==0.2.0 from https://files.pythonhosted.org/packages/2b/57/18b5a914f6d7994dd349252873169e946dc824328e9a37fd15ed836deedc/invisible_watermark-0.2.0-py3-none-any.whl.metadata
  Using cached invisible_watermark-0.2.0-py3-none-any.whl.metadata (8.2 kB)
Collecting numpy==1.19.2 (from -r /Users/stephane/diffusionmagic/requirements.txt (line 15))
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-install-fl2oawcw/numpy_d7d12de5af1b43d1b577ade3b2cfbfa2/tools/cythonize.py", line 235, in <module>
          main()
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-install-fl2oawcw/numpy_d7d12de5af1b43d1b577ade3b2cfbfa2/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-install-fl2oawcw/numpy_d7d12de5af1b43d1b577ade3b2cfbfa2/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-install-fl2oawcw/numpy_d7d12de5af1b43d1b577ade3b2cfbfa2/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-install-fl2oawcw/numpy_d7d12de5af1b43d1b577ade3b2cfbfa2/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/stephane/diffusionmagic/env/bin/python3.11', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/stephane/diffusionmagic/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/stephane/diffusionmagic/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/stephane/diffusionmagic/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-build-env-c2mzp2q0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-build-env-c2mzp2q0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 249, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9q/7_9z_83j61x1g485zrg8l2mr0000gp/T/pip-build-env-c2mzp2q0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 499, in <module>
          setup_package()
        File "setup.py", line 479, in setup_package
          generate_cython()
        File "setup.py", line 274, in generate_cython
          raise RuntimeError("Running cythonize failed!")
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by vicento** [comment]
if i try start.sh i get :
Starting DiffusionMagic please wait...
Found python command
Python version : 3.11.6
Traceback (most recent call last):
  File "/Users/stephane/diffusionmagic/src/app.py", line 4, in <module>
    from backend.generate import Generate
  File "/Users/stephane/diffusionmagic/src/backend/generate.py", line 5, in <module>
    from backend.stablediffusion.depth_to_image import StableDiffusionDepthToImage
  File "/Users/stephane/diffusionmagic/src/backend/stablediffusion/depth_to_image.py", line 4, in <module>
    from diffusers import StableDiffusionDepth2ImgPipeline
ModuleNotFoundError: No module named 'diffusers'

**Comment by rupeshs** [comment]
Seems like numpy installation failed can you remove numpy from requirements.txt and install it

**Comment by vicento** [comment]
Great the web start now

**Comment by rupeshs** [comment]
@vicento Thank you

**Comment by rupeshs** [comment]
Fixed in the release https://github.com/rupeshs/diffusionmagic/releases/tag/v3.6.0

**Comment by vicento** [comment]
when i try to render an image there is an error at the end (final step) :
➜  diffusionmagic git:(main) ✗ sh /Users/stephane/diffusionmagic/start.sh
Starting DiffusionMagic please wait...
Found python command
Python version : 3.11.6
DEVICE: MPS backend
Model : stabilityai/stable-diffusion-xl-base-1.0
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Initializing stable diffusion xl pipeline
StableDiffusion - mps,torch.float16
using model stabilityai/stable-diffusion-xl-base-1.0
Loading pipeline components...: 100%|████████████████████████████████████████████████████████| 7/7 [00:15<00:00,  2.26s/it]
Model loaded in 16.56s 
loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/495c257e-668e-11ee-93ce-926038f30c31/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":233:0)): error: input types 'tensor<1x77x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
/Users/stephane/diffusionmagic/start.sh: line 25: 27940 Abort trap: 6           $PYTHON_COMMAND src/app.py
/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by vicento** [comment]
i have no knowledge to correct that. 
That's ChatGPT analysis :
The error you've encountered seems to be related to a broadcasting incompatibility between two tensors when using a model based on Metal Performance Shaders (MPS). The specific error is:

less
Copy code
loc("varianceEps"("(mpsFileLoc): ...: error: input types 'tensor<1x77x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
This indicates that the code is attempting to perform an operation between two tensors (tensor<1x77x1xf16> and tensor<1xf32>) that aren't compatible in terms of broadcasting.

To resolve this error, here are a few steps you can take:

Check the source code:
Examine the code within src/app.py and any related files to locate where this broadcasting operation is being performed. You're looking for an operation that involves two tensors with the mentioned dimensions.
Ensure dimensions are correct:
One common reason for this kind of error is that a tensor's dimension isn't what it should be. Check the expected dimensions for this particular operation and ensure they are correct.
Fix the broadcasting:
If you've identified the operation in question and are confident in the dimensions of the tensors, try making these tensors broadcasting-compatible. You can use methods like .unsqueeze() or .expand() in PyTorch to adjust the dimensions of the tensors.
Update dependencies:
Sometimes, such an error can be due to incompatible versions of libraries. Ensure that all your dependencies, especially those related to MPS and PyTorch, are up-to-date.
Further troubleshooting:
If you have access to the source code or documentation of the stabilityai/stable-diffusion-xl-base-1.0 model, it might provide additional insights into the expected tensor dimensions and how to preprocess them.

**Comment by rupeshs** [comment]
@vicento seems like issue with mps fp16 data type,float 32 will work

**Comment by rupeshs** [comment]
@vicento  I have updated it, can you try this
git pull
./start.sh
Let me know any issues
