### ISSUE TITLE
Changing PyTorch version

### ISSUE THREAD

**Issue by faminee** [rupeshs/diffusionmagic#12]
Hello,

Sorry I am not familiar with python and wondering how would I downgrade the pytorch library? will it even work?

`    Found GPU0 NVIDIA GeForce GTX 680 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 3.7.
`

**Comment by xdevs23** [comment]
The GTX 680 is actually really old and it has so little VRAM that you probably will run into issues when running AI models on it.

**Comment by rupeshs** [comment]
@faminee it is not possible.
