### ISSUE TITLE
./start.sh: ligne 5: micromamba : unknow commande

### ISSUE THREAD

**Issue by 6-ril** [rupeshs/diffusionmagic#14]
Hi, 
I'm not sure if it's an issue or if this is normal, but to get it working with Mint, I had to copy the result of Mamba initialize in the start.sh file.

This content, that is given by install.sh :
```
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!

...

# <<< mamba initialize <<<
```

To start.sh, before the line 
`eval "$(micromamba shell hook --shell=bash)"`

So there's maybe something to do with the install script (but I'm not good enough with shell to advise anything) or me be you can just add this explanation to the Readme.md file ...

Thanks for diffusionmagic !!

Cyril

**Comment by rupeshs** [comment]
@6-ril 
I have removed micromamba. Can you try this
`git clone https://github.com/rupeshs/diffusionmagic/`
`cd diffusionmagic`
`chmod +x install-mac.sh`
`./install.sh`
start using `start.sh`

**Comment by rupeshs** [comment]
Fixed in the latest release https://github.com/rupeshs/diffusionmagic/releases/tag/v3.6.0

**Comment by 6-ril** [comment]
Great !
This is working fine now.

Thanks

**Comment by rupeshs** [comment]
@6-ril Thank you
