### ISSUE TITLE
Mac M1 Error

### ISSUE THREAD

**Issue by beansfotos** [rupeshs/diffusionmagic#5]
When trying to install on an M1 Mac, the command line returns this error:

beans@Beanss-MacBook-Pro diffusionmagic % ./install-mac.sh
./install-mac.sh: line 6:  2284 Killed: 9               $BASEDIR/tools/mac/micromamba -r $BASEDIR/env create -y -f $BASEDIR/environment.yml
./install-mac.sh: line 7:  2285 Killed: 9               $BASEDIR/tools/mac/micromamba shell init -s bash -p $BASEDIR/umamba
Diffusion magic installation completed,press any key to continue...

And a pop-up opens on the screen saying:
![image](https://github.com/rupeshs/diffusionmagic/assets/131821939/a168a92c-ab51-4498-bbd7-9a07015e41f3)
"
![SCR-20230918-9t1](https://github.com/rupeshs/diffusionmagic/assets/131821939/de89f35d-36fc-4761-82df-1c3973e80637)

**Comment by rupeshs** [comment]
@beansfotos  fixed in the latest release https://github.com/rupeshs/diffusionmagic/releases/tag/v3.6.0
