### ISSUE TITLE
Fresh Install, error upon launch

### ISSUE THREAD

**Issue by rugabunda** [rupeshs/diffusionmagic#7]
Git cloned from the repo, then installed successfully on a Windows 11 machine. RTX 3080TI

```
PS D:\ai\image\diffusionmagic> .\start.bat
Starting DiffusionMagic please wait...
Traceback (most recent call last):
  File "D:\AI\Image\diffusionmagic\src\app.py", line 3, in <module>
    from backend.computing import Computing
  File "D:\AI\Image\diffusionmagic\src\backend\computing.py", line 1, in <module>
    import torch
  File "D:\AI\Image\diffusionmagic\env\envs\diffusionmagic-env\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 182] The operating system cannot run %1. Error loading "D:\AI\Image\diffusionmagic\env\envs\diffusionmagic-env\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
```

**Comment by rupeshs** [comment]
@rugabunda Did you followed the instructions here https://github.com/rupeshs/diffusionmagic#how-to-install-and-run-on-windows

**Comment by rugabunda** [comment]
> @rugabunda Did you followed the instructions here https://github.com/rupeshs/diffusionmagic#how-to-install-and-run-on-windows

Yes. Then I ran the installer a second time, on top of the first install. It doesn't appear the first install missed anything. The second install also completed successful, and this error occurs on launching start.bat

**Comment by rugabunda** [comment]
I used git clone to get my copy. I'll try a second install using official release 3.5.0.

**Comment by rugabunda** [comment]
I am getting the exact same error.

**Comment by rupeshs** [comment]
Can you try the latest release https://github.com/rupeshs/diffusionmagic/releases/tag/v3.6.0

**Comment by rugabunda** [comment]
> Can you try the latest release https://github.com/rupeshs/diffusionmagic/releases/tag/v3.6.0

Working now! Thank you :)
